version: 0.2
phases:
  install:
    commands:

      build:
        commands:
          - sam build
          - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged.yaml --s3-bucket lambda-build-artifacts
        artifacts:
          files:
            - packaged.yaml
